# Generated by Django 4.0.6 on 2022-08-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='lastname',
            new_name='email',
        ),
    ]
