# Generated by Django 4.0.6 on 2022-08-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_lastname_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usermaster',
            name='is_created',
        ),
        migrations.RemoveField(
            model_name='usermaster',
            name='is_updated',
        ),
        migrations.RemoveField(
            model_name='usermaster',
            name='is_verified',
        ),
    ]
