# Generated by Django 4.0.6 on 2022-08-03 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_usermaster_email_usermaster_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='otp',
        ),
    ]
